### ISSUE TITLE
Retained button gone

### ISSUE THREAD

**Issue by realjax** [thomasnordquist/MQTT-Explorer#108]
When connecting to a  broker that has a subject with a retained message, the retained [x] button is shown. When a new message is received the topic value are updated but the retained button disappears , even though the new message was also set to retain.
When disconnecting and reconnecting again, the retained button is shown again.

**Comment by thomasnordquist** [comment]
That is perfectly normal.
The retain flag is intended to differtiate between live messages and retained/"out-of-date" messages.
When you receive a retained message you have no way to know how old it is.
When publishing you set "retain" to persist the message on the broker, when you subscribe to a topic and the broker has retained topics matching your topic selector it will send you all the retained topics immediatly, sending the retain flag so you know the message is not a live event.

If you got further questions, I'll try to elaborate. It's not a bug. MQTT v5 has a "retain expiary" that automatically removes retained messages at a given time.

**Comment by realjax** [comment]
Thanks, makes sense. So if I understand this correctly there's no other way to find out one has succesfully set the retain flag then by subscribing to it (again) ?

Thomas Nordquist <notifications@github.com> schreef op 17 april 2019 23:52:03 CEST:

**Comment by thomasnordquist** [comment]
Yes.
Also, to clear a retained topic, you need to send a retained empty message. (just an empty string)
