### ISSUE TITLE
how can i install armbian ?

### ISSUE THREAD

**Issue by halukmy** [thomasnordquist/MQTT-Explorer#111]
thanks

**Comment by thomasnordquist** [comment]
I am not certain what your request is.
MQTT Explorer can run on a multitude of ARM processors.
This might help you: https://github.com/thomasnordquist/MQTT-Explorer#run-from-sources

You might also want to check out the https://github.com/thomasnordquist/MQTT-Explorer/releases/download/0.0.0-v0.2.5/MQTT-Explorer-0.2.5-armv7l.AppImage
