### ISSUE TITLE
[Question] Docker image 🐳

### ISSUE THREAD

**Issue by cecchisandrone** [thomasnordquist/MQTT-Explorer#113]
Hey @thomasnordquist , nice project, probably the best one. What do you think about providing a Docker image?
Thanks

**Comment by thomasnordquist** [comment]
The issue with docker and UI applications is that you need to forward the X-server.
It would only run on 64bit Linux, maybe MAC if XQuartz is installed.

It is certainly doable.
What is your motivation / why is it important to you?

**Comment by cecchisandrone** [comment]
Sorry, I just have noticed that it is a desktop app and not a web app.

**Comment by thomasnordquist** [comment]
It is planned to become also a web-app, as part of 
https://github.com/thomasnordquist/MQTT-Explorer/issues/60
https://github.com/thomasnordquist/MQTT-Explorer/issues/64

It will still require a server component to connect via TCP (browsers only allow http or websocket connections).

Then containerizing is definitely a good idea.

**Comment by thomasnordquist** [comment]
Still a lot to do till this becomes relevant.
