### ISSUE TITLE
Graph displays strange lines

### ISSUE THREAD

**Issue by mrwee** [thomasnordquist/MQTT-Explorer#114]
Looking at a graph for a binary value, I sometimes see it drawn a bit funny. Please see attached screenshot. Running 0.2.3.
![2019-05-03_20-05-55](https://user-images.githubusercontent.com/6720774/57156805-34a6ec00-6ddf-11e9-8937-953ac8a05564.png)

**Comment by thomasnordquist** [comment]
This is art, it is supposed to look like this.
I'll have a look 🤯

**Comment by thomasnordquist** [comment]
Fixed with 9e15e2814743859775a77be5638d42c0ef6d295d

**Comment by thomasnordquist** [comment]
Will be released the next few days

**Comment by mrwee** [comment]
Great! You're doing a great job with MQTT Explorer! Really love it :)
