### ISSUE TITLE
Client Cert Auth instead of PSK?

### ISSUE THREAD

**Issue by AgentBignose** [thomasnordquist/MQTT-Explorer#118]
Would it be possible to give an option to also attach a Client public key to authenticate?

**Comment by thomasnordquist** [comment]
Do you want it because you want to use AWS IoT?
I added an issue for this a long time ago, but I believe it should be pretty simple to support it by now: https://github.com/thomasnordquist/MQTT-Explorer/issues/17

**Comment by AgentBignose** [comment]
I want to use it for EdgeDevices in my company. In Production we would rather want to have the gateways login with their signed certs using FQDN as user than have PSK credentials stored on them.

Could that work with MqttNet?
The lib has been a big help for me with its ManagedClient and the auto connect feature!
Thx a lot for your work!

**Comment by thomasnordquist** [comment]
I added support for client certificates, initial tests look promising.
You can check it out here:
https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.0.0-0.3.1-alpha-sni

You can set the certificates at:
Advanced Settings => Certificates

Please tell me if you run into any trouble

**Comment by AgentBignose** [comment]
Very cool!
Seems do work well.
I tested with a mosquitto broker with following settings:

`#allow_anonymous false
#password_file /etc/mosquitto/pass.txt
listener 8883
cafile /home/steve/mos/certs/ca.crt
keyfile /home/steve/mos/certs/server.key
certfile /home/steve/mos/certs/server.crt
require_certificate true
use_identity_as_username true`

If I add Server crt, client crt and client key to MQTT Explorer, I can connect, like I should.
If I dont configure client key, mosquitto rejects Connection and MQTT Explorer gives a "Disconnect from server" like it should.
If I configure Client Key but no client cert,  mosquitto rejects Connection and MQTT Explorer gives a "Disconnect from server" like it should.

In UI under Advanced Client Cert and Key Buttons go to the same line when only one of them is configured. If you configure Client Key first, it will be displayed below Client Cert Button, that could be irritating.

Excellent! Thx a lot for implementing!

**Comment by thomasnordquist** [comment]
The UI still needs some love, but I thought you would appreciate the prototype 😉

**Comment by AgentBignose** [comment]
Yes absolutly! I very much appreciate it.
Your tool is running on my screen day and night now, very practical and same time resource friendly. I was worried about this part in the beginning.

Now I need to find out how to enable PSK and Client Cert Auth on VerneMq and mosquitto at the same time.

**Comment by thomasnordquist** [comment]
Will be released for all platforms in 0.3.2, currently build into Ubuntu snap releases and 0.3.1 pre-release.

**Comment by thomasnordquist** [comment]
Released with [v0.3.5](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5).
