### ISSUE TITLE
Option to set CA for self-signed certs

### ISSUE THREAD

**Issue by AgentBignose** [thomasnordquist/MQTT-Explorer#134]
With Client Cert auth under devlelopment [now ](https://github.com/thomasnordquist/MQTT-Explorer/issues/118) it would be nice to be able to set your own CA you used to self-sign your server and client crts.

Without this option you have to disable "Validate certificate".

Unfortunetly many companies do not sign their Root Crts externally :-( :-(

**Comment by thomasnordquist** [comment]
That is already possible, look for `Server Certificate` in the certificates tab (not sure if the naming is 100% accurate)

**Comment by thomasnordquist** [comment]
@AgentBignose does this answer your question?

**Comment by AgentBignose** [comment]
Oh yes, sorry! This morning I confused this with the server public key.

This does answere my question!

**Comment by thomasnordquist** [comment]
Released with [v0.3.5](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5).

**Comment by mrdc** [comment]
@thomasnordquist 

Hi Thomas,

Maybe a better way would be to provide a `server.crt` in `mqtt-explorer` settings and validate it against `ca.crt` which is in system root of trust.
So, I install my `ca.crt` system wide and all `server.crt's` signed by that `ca.crt` are automatically become valid.
