### ISSUE TITLE
Aliases for topics

### ISSUE THREAD

**Issue by matsekberg** [thomasnordquist/MQTT-Explorer#138]
A feature to set an alias on a topic (and subtopic) would be nice.
And an option how to display the alias and topic:

- Topic only
- Topic and alias
- Alias only

**Comment by thomasnordquist** [comment]
Where exactly? For the Charts?

**Comment by matsekberg** [comment]
In the tree to the left.

Med vänlig hälsning, Mats

**Comment by thomasnordquist** [comment]
I am uncertain if this is a feature that people will understand and use.
In my opinion, the tree should be a purely technical view and not obfuscate the real topic names.

I also get that often there is a need to associate a purely technical "ID" with something real.

I, for instance, use aliases in my mqtt topics whenever I can.
This may work well for home automation but not so well with flat hierarchies in industrial applications.

## I also republish topics to achieve better readability
All topics in `zigbee` have been derived from `zigbee2mqtt` and additional knowledge I have about these devices
<img width="771" alt="Bildschirmfoto 2019-06-24 um 13 51 00" src="https://user-images.githubusercontent.com/7721625/60016662-22cb2200-9687-11e9-8410-eacf33f7dfc7.png">

If you still think aliases are important, please describe in greater detail what you have envisioned.
(Maybe even take screenshot illustrate with Paint / Gimp / Photoshop)

**Comment by matsekberg** [comment]
I agree in your analysis. 
It might clutter the clean and outstanding interface.

Med vänlig hälsning, Mats
