### ISSUE TITLE
Scrollable Connections List

### ISSUE THREAD

**Issue by AgentBignose** [thomasnordquist/MQTT-Explorer#147]
Having a scrollable Connections List would be good.

By now the App is so helpful I use it with many brokers and with more then 9 one can not access #10 anymore.

**Comment by thomasnordquist** [comment]
holy ****
I have seen this screen for like a thousand times, never considered scrolling an issue.
Thanks a lot!

**Comment by thomasnordquist** [comment]
Fixed with 77dcbccd5c69d2d048ffa0baf10538c53844cf9d, will be released soon.

**Comment by thomasnordquist** [comment]
Released with [v0.3.5](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5).
