### ISSUE TITLE
Set time-range for curves

### ISSUE THREAD

**Issue by tseroo** [thomasnordquist/MQTT-Explorer#148]
Really cool tool! Helps a lot in working with MQTT. Thanks for that!

One request though.. would be great to be able to set the time range for the curves, e.g. from 'now-5m' to 'now'. Would help a lot to be able to focus on the last few minutes only, especially during troubleshooting/testing flows.

**Comment by thomasnordquist** [comment]
You are correct, this will be a good addition.
I nicht also add a Auto-Range option.

**Comment by thomasnordquist** [comment]
The time range can now be selected, I also increased the limit of data points from 99 to 500 for charts in the chart panel.

The release will be out in the next view days =)

<img width="836" alt="Bildschirmfoto 2019-07-07 um 23 15 41" src="https://user-images.githubusercontent.com/7721625/60773957-35286f80-a10d-11e9-990d-d1905468a576.png">

**Comment by marc-gist** [comment]
you are awesome! Thanks for a great tool... could you also allow the data point count be user set? You've changed to 500, which is typically going to be plenty.  but i do have some sensors that report very frequently and I would sometimes want to track more than that (yes, memory may become an issue, so perhaps that setting isn't saved/stored between restarts in case of a crash).

**Comment by thomasnordquist** [comment]
That is the plan. Since I'm currently quite busy, I opted for the minimal-effort option of setting a fixed value and add this option at a later time 😅

**Comment by thomasnordquist** [comment]
The feature will is tracked here: https://github.com/thomasnordquist/MQTT-Explorer/issues/150

**Comment by thomasnordquist** [comment]
Released with [v0.3.5](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5).
