### ISSUE TITLE
Payload text is truncated

### ISSUE THREAD

**Issue by balvant813** [thomasnordquist/MQTT-Explorer#153]
My mqtt payload are long (170-200 chars). They get truncated in MQTT explorer. 

payload is:
`{"Timestamp":"1562979185","SentBY":"RadarTimerOff","motionTSt":"Motion","radar":"ON","light":"ON","fan":"OFF","Time":"7/13/2019 0:53:5","IP":"211","Ver":"V-071019-2p13"}`

in MQTT Explorer (ver 0.3.0 Win), it shows as:
`d1mini_221_mbtoiletswitch = {"Timestamp":"1562979185","SentBY":"RadarTimerOff","motionTSt":"Motion","radar":"ON","light":"ON","fan":"OFF","Time":"7/`

Is there a way to see the full payload?

**Comment by thomasnordquist** [comment]
If you click on a topic it will appear on the right side, there you can copy it.

![screen3 (3)](https://user-images.githubusercontent.com/7721625/61169503-cf017980-a55e-11e9-8f24-b94c563be622.png)

Truncating the payload is "important" for big brokers with thousands of messages.
It allows making assumptions on memory consumption and render speed. I'll see if I can find a smarter approach.

There is also a small video on https://mqtt-explorer.com/, showing off some of the features of MQTT Explorer.

**Comment by thomasnordquist** [comment]
I also increased the length of the text, and let the layout engine decide if the text needs truncating.
