### ISSUE TITLE
Add Light/Dark theme switch

### ISSUE THREAD

**Issue by thomasnordquist** [thomasnordquist/MQTT-Explorer#16]
I used the theme in most places, evaluate effort. Should be straight forward.

**Comment by thomasnordquist** [comment]
Part of 6853066a1910dca95c7034b3d04ef1c4a9447015 and 6f86a8d471943a71357010460bf9cf85dd7cd49a.

Still fixing a few styling issues as they occur, can be considered complete.

**Comment by Slyke** [comment]
Was this ever merged?
