### ISSUE TITLE
Is it possible to run in browser mode?

### ISSUE THREAD

**Issue by podarok** [thomasnordquist/MQTT-Explorer#171]
Hi.
Thank you for the great product.
Given the fact Electron browser has no support for Android - is there any chance to use this app in browser only mode?

**Comment by thomasnordquist** [comment]
I planned it once, but to be honest this would take a considerable amount of time to pull off without losing features.

Problems:
- Webviews do not support TCP sockets (websocket-only support sucks)
  -> backend component needs to run in a different context
- SSL / TLS features  need to be evaluated & certificate selection needs to be rewritten
- Several components need a rewrite to be responsive enough to fit on a small screen.
- Chromium / Browser-specific features need a polyfill.

Some of the stuff regarding browser incompatibility is tracked here:
https://github.com/thomasnordquist/MQTT-Explorer/issues/64

**Comment by thomasnordquist** [comment]
Closing in favor of https://github.com/thomasnordquist/MQTT-Explorer/issues/173
