### ISSUE TITLE
MQTTLens joins MQTT-Explorer

### ISSUE THREAD

**Issue by sandro-k** [thomasnordquist/MQTT-Explorer#181]
Hi Thomas,

MQTT-Explorer looks really good and it has many nice features. I am the author of MQTTLens (https://github.com/sandro-k/mqtt-lens) and haven't had the time to maintain or update the Chrome App as I wanted to. I always planned to start working on a new version, but never got to it. Just this weekend I discovered your app and immediately thought it would make sense to replace MQTTLens by MQTT-Explorer. Yes Chrome Apps are deprecated, but I still have a very active user base on the app and I don't see google shutting it down soon.  I am not sure how much work it is to integrate MQTT-Explorer into a Chrome App, but I thing it is worth a discussion. 

Let me know what you thing.
Sandro

**Comment by thomasnordquist** [comment]
I have been thinking a lot about it today.
What I love about MQTTLens is that it sticks to the basic principles of publish&subscribe.
MQTT Explorer takes a lot the "getting to know mqtt" away.

I think it is fairly simple to adapt MQTT Explorer as a Chrome App. I am however a little bit worried about the TCP / TLS connections and custom certificates.
Things that need to be evaluated:
- [MQTTjs](https://github.com/mqttjs/MQTT.js) and Chrome App sockets (TLS via TCP would be very very nice, possibly with custom certificates). MQTTjs is not a neccessity but the library is very mature
- Evaluate if we need a new settings storage solution (key/value storage attached to an event-emitter). Currently I used `lowdb` [in here](https://github.com/thomasnordquist/MQTT-Explorer/blob/master/backend/src/ConfigStorage.ts).
- Certificate selection is currently electron-specific

I by the way love MQTTLens for its simplicity! I would like to retain this simplicity.
I am also not sure if we should replace MQTTLens, I think people still love it a lot.

What do you think?

**Comment by sandro-k** [comment]
Currently MQTTLens is not offering any SSL. It would be nice to get it Integrated at some point but I think it it not 100% necessary in the first step. 

I would try with the following 
1. Map MQTTLens settings (JSON-Object) to MQTT-Explorer
2. Make MQTT-Explorer aware to detect available features like SSL 
3. Bundle as Chrome App

Yes I like the simplicity of the MQTTLens interface too. Maybe on the Chrome side it could be a MQTT-Exlorer lite version, with less features and a simple UI, but with the same backend .If users like to have more functionality we could make them aware of the full MQTT-Explorer version.

Currently I use MQTT.js with a TCP Chrome wrapper to allow MQTT connections via TCP.

**Comment by thomasnordquist** [comment]
I though about it a lot and came up with a few reasons not to continue with this effort:
- According to [google's annoucement](https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html) the chrome apps should have seized to work in 2018.
- Missing TLS (via TCP) and no way of setting custom TLS certificates is a very big drawback. (You shouldn't connect to a mqtt broker without encryption)
- Time (This would at least take a few days to achieve)
- People like your app the way it is
