### ISSUE TITLE
AlternativeTo listing

### ISSUE THREAD

**Issue by edorgeville** [thomasnordquist/MQTT-Explorer#192]
Hi there,

A coworker made me discover this app last week and it is such a game-changer! Perfect for topic discovery, handling large amounts of data, etc. I wish it existed back when I was looking for an MQTT client.
Everytime I'm looking for a program to accomplish a task, I head to [alternativeto.net](https://alternativeto.net). That's how I landed back then on MQTTBox.

Now I want people to be able to find this one! I made a listing today that just got approved :  
https://alternativeto.net/software/mqtt-explorer/

Thanks for this wonderful piece of software, @thomasnordquist. Keep up the good work.
Cheers!

**Comment by thomasnordquist** [comment]
Nice, thanks for promoting! Never though of alternativeto.net as a platform 😅
