### ISSUE TITLE
Please provide builds for download

### ISSUE THREAD

**Issue by probonopd** [thomasnordquist/MQTT-Explorer#2]
https://github.com/thomasnordquist/MQTT-Explorer/blob/b44f35280405ae10658cdaa3c39084b36cc8ec13/build.ts#L8

Please provide those builds for download on GitHub Releases, thank you.

**Comment by thomasnordquist** [comment]
I first wanted to fix some stuff and get the CI up and running.

Viel Spaß!

**Comment by probonopd** [comment]
Dankeschön! :+1:
