### ISSUE TITLE
Support for Secure Websocket

### ISSUE THREAD

**Issue by aestrro** [thomasnordquist/MQTT-Explorer#207]
Firstly, I love the project. Is there a way you can add Secure WebSockets (e.g. wss:// ) as an option?

**Comment by thomasnordquist** [comment]
Adjust to the correct TCP Port, and enable "Encryption (tls)". Don't forget that you often need a basepath for websocket connections (`ws` in most cases). 

<img width="1028" alt="Bildschirmfoto 2019-09-13 um 11 21 37" src="https://user-images.githubusercontent.com/7721625/64851921-abb78100-d618-11e9-99e3-a3befbe66e10.png">

**Comment by aestrro** [comment]
That did it, sorry for the noise.
