### ISSUE TITLE
Right side of UI not completely visible

### ISSUE THREAD

**Issue by satoer** [thomasnordquist/MQTT-Explorer#219]
The right side of the UI is not visible. See screenshot:
https://i.postimg.cc/y8QtbWqY/mqtt-explorer-ui-not-visible.png
does not matter if I rescale the window or maximize it. Now I cant see or press the "publish" button also.
Used on Windows 10 on a 4k monitor.

**Comment by thomasnordquist** [comment]
Close the settings panel 😉
