### ISSUE TITLE
Publish button disappears

### ISSUE THREAD

**Issue by KorbinianSchilling** [thomasnordquist/MQTT-Explorer#227]
When I copy my JSON object as an unformatted one liner which is much longer than the given textbox and I hit "Publish", the publish-button disappears towards the right end of the text box. Therefore, it is no longer possible for me to publish further messages.
See attached the screenshots for further clarification. 

Example json:
`{"test7":"11111111111111111111111111111111132222222222222222222222222222222222222555555555555555555555", "test3":"11111111111111111111111111111111132222222222222222222222222222222222222555555555555555555555", "test5":"11111111111111111111111111111111132222222222222222222222222222222222222555555555555555555555","test":"11111111111111111111111111111111132222222222222222222222222222222222222555555555555555555555","test1":"11111111111111111111111111111111132222222222222222222222222222222222222555555555555555555555","test2":"11111111111111111111111111111111132222222222222222222222222222222222222555555555555555555555"}`

![mqtt_1](https://user-images.githubusercontent.com/45166454/67459431-e27daf80-f638-11e9-87c6-44ce653c3dc4.png)
![mqtt_2](https://user-images.githubusercontent.com/45166454/67459433-e27daf80-f638-11e9-8ba2-1423b3d6188f.png)
![mqtt_3](https://user-images.githubusercontent.com/45166454/67459435-e3164600-f638-11e9-8737-17cef359d153.png)

**Comment by thomasnordquist** [comment]
It appears that the message history is the culprit here.
Definitely a bug, I'll see that I'll get that fixed in the near future!

Thanks for the report!

**Comment by skippy-oz** [comment]
I'm also having the same problem

**Comment by LordMike** [comment]
Still present in `0.3.5` :)

**Comment by CptHolzschnauz** [comment]
Still there

**Comment by tophee** [comment]
How are people working around this? Or has MQTT Explorer become more or less unusable (at least when it comes to publishing)?

**Comment by LordMike** [comment]
@tophee it is not present for me, in `0.4.0-beta1`

**Comment by tophee** [comment]
Oh, that's good to know. From what I read in #480, though, the beta doesn't work on Big Sur (which is what I'm using) so I'll have to wait for the release... Not sure when that'll be, given that the beta is already a year old.

**Comment by stefan-sherwood** [comment]
I just spent 10 minutes trying to figure out how to publish before I Googled and came across this. I shutdown and restarted MQTT Explorer and the Publish button came back.

`0.4.0-beta1`

**Comment by dwightfowler-cd** [comment]
Hey, it's June 7th of 2021. Can we fix this, please?
Oct 24, 2019 to June 7, 2021 = 592 days

**Comment by stefan-sherwood** [comment]
This issue was closed 18 months ago. Not sure what you mean by "we" but you are certainly welcome to create a pull request with a fix.

**Comment by dwightfowler-cd** [comment]
Stefan,
Thanks for replying. I guess I mean that the latest version still has the issue. I’m not opposed to digging, just thought the reply about fitting it on the next release had been lost.

Sorry for the troll-like post. It’s been a bad day.


Thanks,


Dwight

**Comment by stefan-sherwood** [comment]
No worries. I'm mainly just pointing out that a long-closed issue with a known workaround is unlikely to see much action.

**Comment by dwightfowler-cd** [comment]
Stefan,
Sheesh, I TL;DR-ed the whole beta work around. Apologies again, and thanks for your kind responses.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
