### ISSUE TITLE
Windows installer or protable option .exe is not trusted be Windows Defender

### ISSUE THREAD

**Issue by nurquhar** [thomasnordquist/MQTT-Explorer#250]
If run the installer or portable EXE I get the following warning on my Win10 PC:

Windows protected your PC
Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

![image](https://user-images.githubusercontent.com/34193510/69369758-85efcd80-0c94-11ea-8e98-2f83e4c63f04.png)

**Comment by thomasnordquist** [comment]
Well you could press `Run anyway` or use the App from the Microsoft Store.

I would need to buy a certificate for a few hundred euros to make the defender trust the app, it's simply not worth the money / effort. The App from the Microsoft Store works fine.
