### ISSUE TITLE
Add drop-down in connect dialog with previous broker successful connections

### ISSUE THREAD

**Issue by vzorglub** [thomasnordquist/MQTT-Explorer#26]
Please add a drop-down in the connect dialog to be able to select a previous successful connection
Maybe add an alias for each connection to be able to select the relevant broker/connection.

**Comment by thomasnordquist** [comment]
I plan to have a list with brokers on the left side, with edit, update and delete options.

More or less a duplicate of:
https://github.com/thomasnordquist/MQTT-Explorer/issues/15
