### ISSUE TITLE
JS keys with periods in them cause issues with charts

### ISSUE THREAD

**Issue by mmattice** [thomasnordquist/MQTT-Explorer#281]
<img width="550" alt="Screen Shot 2020-01-07 at 6 19 16 PM" src="https://user-images.githubusercontent.com/302396/71940015-5f212400-317a-11ea-86e5-70451096443d.png">
<img width="562" alt="Screen Shot 2020-01-07 at 6 19 07 PM" src="https://user-images.githubusercontent.com/302396/71940016-5f212400-317a-11ea-8817-76d6aff991cd.png">
The resulting chart gets a header like so, indicating a quoting issue.
<img width="439" alt="Screen Shot 2020-01-07 at 6 18 28 PM" src="https://user-images.githubusercontent.com/302396/71940038-7102c700-317a-11ea-88e1-b9df8742541d.png">

**Comment by thomasnordquist** [comment]
Well, yes this is a real bug...
Currently using https://www.npmjs.com/package/dot-prop to extract the values from JSON.

The dot in "3.3" needs to be escaped.

I'll see that I do a release with the fix soon.

**Comment by thomasnordquist** [comment]
Thanks for your bug-report =)
