### ISSUE TITLE
Constant disconnecting and reconnecting

### ISSUE THREAD

**Issue by voltagex** [thomasnordquist/MQTT-Explorer#283]
Any ideas what's going on here?

![disconnect](https://user-images.githubusercontent.com/159567/72214338-ee9c4d80-3553-11ea-90a4-d86af267f870.gif)

This is connected to a mosquitto 1.5.7 server, no config changes, just started disconnecting and reconnecting when I started MQTT Explorer. This version is installed via the Windows store

**Comment by thomasnordquist** [comment]
You have most likely two instances of MQTT Explorer open:
The server will disconnect clients with the same client-id.
Both MQTT Explorer instances then try to reconnect, and get disconnected
again.

**Comment by thomasnordquist** [comment]
Related to #226, #132.
Closing it since it is a duplicate.

**Comment by zachj316** [comment]
I am having the same problem. I opened my task manager in windows 11 and searched my task for MQTT and closed all instances. I then reopened it one time with the same problem. I want back in task manager and it says mqtt explorer(4), which I assume means one instance four windows. I have the problem previously described. Constantly disconnecting and reconnecting
