### ISSUE TITLE
Auto Discovery

### ISSUE THREAD

**Issue by Anjerlaan** [thomasnordquist/MQTT-Explorer#284]
Hi,

When I connect to my zigbee2mqtt network, only my CC2530 Router is auto discovered by the explorer.
I also have an IKEA remote + a Group of 3x GU10 IKEA bulbs in the zigbee2mqtt network.
The only way to discover them in the explorer is:
- The IKEA Remote: **Pressing a button**
- Group and 3x GU10 bulbs: **Send a group state command** (zigbee2mqtt/Keuken_Spots/set)

Why is this?

**Comment by thomasnordquist** [comment]
Well, MQTT Explorer can only see messages which have been published by `zigbee2mqtt`.
If you always want to "see" the last state of each device you should check put the persist option of zigbee2mqtt. Be aware that it may change the behavior of your devices / home-automation.

**Comment by Anjerlaan** [comment]
Okay, thanx for the info!
