### ISSUE TITLE
Keyboard shortcut for copy doesn't work on Mac

### ISSUE THREAD

**Issue by rherban** [thomasnordquist/MQTT-Explorer#291]
Running on Mac Catalina with MQTT Explorer 0.3.5

Love the app and it's greatly helped me understand the layout for the new position I've taken over, but one bug I've found is trying to select a portion of the message and copying with Command-C.  I see that I can copy the entire message with the copy icon, but our messages are json blobs and I need to grab specific text from it.  

I can copy using the Edit menu, but not with the keyboard shortcut.  

Thanks!

**Comment by gizmocuz** [comment]
Unfortunately it also does not work on windows

**Comment by Xedecimal** [comment]
Cut also does not work, and you guessed it, paste doesn't either. This is due to anything you type going straight into the search field regardless of modifier keys. This is the only issue I have with this thing.

**Comment by thomasnordquist** [comment]
Should be fixed with fbfbe94d196a9c19601e28633ad363e252850da4.
Providing a beta release soon.

**Comment by gizmocuz** [comment]
Compiled/Tested under Windows, this works great ! Thanks

**Comment by thomasnordquist** [comment]
Thank you very much for confirming the fix 👍
