### ISSUE TITLE
Password field overwrites username

### ISSUE THREAD

**Issue by dave12311** [thomasnordquist/MQTT-Explorer#292]
Typing in the password field overwrites text in the username field.
![](https://media.giphy.com/media/h5v17D33Yz50rE7TPb/giphy.gif)

**Comment by thomasnordquist** [comment]
Well, that's indeed weird 😅
Which version are you using? I cannot reprodice it with the current release.

**Comment by dave12311** [comment]
It was the latest on master and I'm using Manjaro KDE.
The only error message I can see is:
`Gtk-Message: 17:46:27.253: Failed to load module "appmenu-gtk-module"
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.`

**Comment by thomasnordquist** [comment]
Thanks for the bugreport. 
Found it and fixed it.
