### ISSUE TITLE
Add navigation via arrow keys

### ISSUE THREAD

**Issue by CWempe** [thomasnordquist/MQTT-Explorer#30]
It would be nice to use arrow keys to navigate thou the topics.

Use left,/right to expand/collapse topics

**Comment by thomasnordquist** [comment]
That's a tricky one, but a nice feature.

**Comment by thomasnordquist** [comment]
Navigation via arrow key has been implemented.
Will be part of 0.3.2 (0.3.1 supports it, is only released for ubuntu snap store as part of a critical bugfix).

As part of this issue other keyboard interactions have been added:
- "Search as you type" (filter tree without previously selecting the search bar)
- Broker profile selection with <kbd>↑</kbd> and <kbd>↓</kbd>, connect with <kbd>⏎ Enter</kbd>, abort connection with <kbd>Esc</kbd> and <kbd>⏎ Enter</kbd>
- <kbd>Tab</kbd> element selction order has been imroved
- Fix range selection with <kbd>Tab</kbd> in Chart settings
- Navigate tree with <kbd>↑</kbd>, <kbd>↓</kbd>, <kbd>←</kbd>, <kbd>→</kbd>.  
  Delete (retained) topics / partial trees with <kbd>Del</kbd> or <kbd>Backspace</kbd>

Missing:
- Split-view cannot yet be controlled via the keyboard

**Comment by thomasnordquist** [comment]
Released with [v0.3.5](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5).
