### ISSUE TITLE
Add graph for history of values

### ISSUE THREAD

**Issue by CWempe** [thomasnordquist/MQTT-Explorer#31]
It would be nice if you could open a graph generated with the last received values of a topic.

This would be usefull for debugging sensors like temperature etc.

Just an idea 😉

**Comment by thomasnordquist** [comment]
<img width="1188" alt="bildschirmfoto 2019-01-19 um 18 57 54" src="https://user-images.githubusercontent.com/7721625/51430498-6d4dfb80-1c1c-11e9-93ec-5287862a7b4b.png">
