### ISSUE TITLE
Screen Stays black with latest 0.3.5/0.3.6 on Win10

### ISSUE THREAD

**Issue by haniham** [thomasnordquist/MQTT-Explorer#319]
Hello,

On a quite freshly installed Win10 the screen stays black after starting.

Used Versions:
- 0.3.5 Windows store
- 0.3.5 Setup from git
- 0.3.5 "portable" exe
- 0.3.6 "portable" exe
- 0.3.0 "portable" exe

Attempts to start with the "x --debug" option result in the same black screen

Help is greatly appreciated

![grafik](https://user-images.githubusercontent.com/4102949/76164716-508ec300-6151-11ea-8566-c2881cfe48dd.png)
[Roaming-MQTT-Explorer.zip](https://github.com/thomasnordquist/MQTT-Explorer/files/4303318/Roaming-MQTT-Explorer.zip)
[DxDiag.txt](https://github.com/thomasnordquist/MQTT-Explorer/files/4303323/DxDiag.txt)

**Comment by thomasnordquist** [comment]
You could test https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/0.4.0-beta1

**Comment by haniham** [comment]
Sorry for the long time - created this issue for a friend

It seems to work now perfectly fine with the 0.3.6-no-delete-limit version

![grafik](https://user-images.githubusercontent.com/4102949/81509448-17b6ca00-930b-11ea-9da1-69e645f96b2c.png)

Thanks much
