### ISSUE TITLE
Cannot run dev mode

### ISSUE THREAD

**Issue by pigeek** [thomasnordquist/MQTT-Explorer#322]
Environment - Win10
yarn build/yarn start - work fine
yarn dev - ends with endless "Waiting for dev server".

If I go manually to http://localhost:8081/, I see that the browser is able to load some bundles.

What I am missing?

**Comment by thomasnordquist** [comment]
I'll have a look, need to download and setup a VM first 😅

**Comment by thomasnordquist** [comment]
Ahh. just happened to me too.

The application expects that the TCP port 8080 is available (not in use by any other application).
If it is not available the development server will use the next best tcp port (8081 in your case)
