### ISSUE TITLE
Deleting a lot of topics, does not complete

### ISSUE THREAD

**Issue by LordMike** [thomasnordquist/MQTT-Explorer#333]
I've stopped my HASS and Zwave2MQTT brokers, to ensure they're not messing about - and then I issue a "delete all" to a `zwave2mqtt/` root.

![image](https://user-images.githubusercontent.com/1027111/78355597-3e683f00-75ae-11ea-92a9-e3ef14ad02dc.png)

The deleting starts (pushing retained blank messages), but then suddenly it just stops. I've opened the dev console and watched the console to see if any errors occurred, but I only get the following three messages.

It could indicate that the recursive walking (if that's what's happening?) hits some error after the first few topic prefixes.

![image](https://user-images.githubusercontent.com/1027111/78355582-37413100-75ae-11ea-911c-a9fbc5bd4402.png)

In the first picture, I select `zwave2mqtt` and click `` which asks to confirm deleting 1000-something topics. Confirming that adds these three console logs:

![image](https://user-images.githubusercontent.com/1027111/78355783-9737d780-75ae-11ea-9897-499ab9bee760.png)

Note: Restarting the app so only the retained messages are present, does not help.

Thanks in advance - and great tool nonetheless :)

Mike.

**Comment by LordMike** [comment]
I'll note that I was happy to find the Delete key was mapped to this, and Enter to the Yes button - after which the selection is on the topic after the deleted ... so I could quickly iterate through them anyways :)

**Comment by thomasnordquist** [comment]
Glad you fond the shortcuts.
There is a limit of 50 topics. It was intended to prevent people from deleting all topics from the public brokers.

The limit has been removed with the 3.6 beta.
