### ISSUE TITLE
Is there any way to embed the MQTT Explorer?

### ISSUE THREAD

**Issue by Nickibu** [thomasnordquist/MQTT-Explorer#337]
Is there any possibility, that the Explorer can be embed in a Website?
I would use it to overview the Message Traffic in my Config Site to overview not only programms but also the message traffic.

**Comment by thomasnordquist** [comment]
Not yet. It's mostly due to security concerns.

Closing in favor of.
https://github.com/thomasnordquist/MQTT-Explorer/issues/173
