### ISSUE TITLE
Messages to topic with subtopics not shown

### ISSUE THREAD

**Issue by mustang64** [thomasnordquist/MQTT-Explorer#338]
I have a topic with subtopics. The messages sent to the subtopics are shown under the _>topic_ item, but the messages sent to _topic_ are not shown.
For example:
_data/sensors/temperature_
_data/sensors/humidity_
The messages sent to _data/sensors/temperature_ are displayed next to the topic name.
The messages sent to _data/sensors_ are not displayed

Nice job!

**Comment by thomasnordquist** [comment]
<img width="1026" alt="Bildschirmfoto 2020-04-15 um 20 54 01" src="https://user-images.githubusercontent.com/7721625/79377008-54391500-7f5b-11ea-8efe-eeb8c06cc3b0.png">

It certainly appear to work.
- Which version of MQTT-Explorer do you use?
- Have you tried publishing to `data/sensors` with `MQTT Explorer`?
- Do your subscriptions include `data/sensors`?

**Comment by mustang64** [comment]
Hello Thoman,
You're right, it works. I use 0.3.5 and I see the data at every level.
Don't know what happened, because I saw nothing, but now it's ok.
Sorry for the inconvenience. I'm a little bit ashamed :)
Thank you.
Nice job!

**Comment by thomasnordquist** [comment]
No worries, I appreciate the effort.
It's better to have a few "false" bug reports than not reports at all =)
