### ISSUE TITLE
Allow copying of selected text from Value or Value History

### ISSUE THREAD

**Issue by kpine** [thomasnordquist/MQTT-Explorer#343]
I am unable to copy selected text from the topic value or value history. Instead, I have to temporarily copy the entire payload (using the copy button), paste into a text editor, and copy the selection I want. It would be nice to just be able to copy the selected text directly.

![image](https://user-images.githubusercontent.com/791794/80396839-1f399600-886a-11ea-930f-796990da4a3d.png)

I can highlight the individual text. Pressing Ctrl-C removes the highlighting as if it were copied, but it's never put into the clipboard.

**Comment by thomasnordquist** [comment]
There is already a fix. I'll provide a beta release which should resolve your issue.
Which operating system do you use?

https://github.com/thomasnordquist/MQTT-Explorer/issues/291

**Comment by kpine** [comment]
Windows 10. I'd be happy to try it out.

**Comment by kpine** [comment]
I'll close, since it's already been confirmed in #291 , but if you can provide the beta for Windows, that'd be great.

**Comment by thomasnordquist** [comment]
You could test https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/0.4.0-beta1.

I'll try to do a store release the next few days.

**Comment by kpine** [comment]
Confirmed using the Windows setup installer. Thanks.
