### ISSUE TITLE
the screen stays black or empty

### ISSUE THREAD

**Issue by miwok72** [thomasnordquist/MQTT-Explorer#35]
Hello,
does not work for me ...
first you see in the middle a few rotating rings, even after a while the screen stays black ...
0.0.7 portable on Win7 64bit
First I installed the 0.0.5 portable, then the version 0.0.7 via setup and then the version 0.0.7 portable (after uninstalling 0.0.7 via uninstall)

**Comment by thomasnordquist** [comment]
Thank you for reporting this issue. You are the second person with this issue, so it is kind of important to me to find out how this happens.
Did the 0.0.5 portable work?

It could be that a configuration is corrupt.

If you want to help me investigate you can probably see the error by editing the desktop shortcut of the MQTT-Explorer. Add ` x --debug` as arguments and the developer console will open.
<img width="395" alt="bildschirmfoto 2019-01-18 um 09 34 06" src="https://user-images.githubusercontent.com/7721625/51374811-6e8c0500-1b04-11e9-8d95-193f8f08e98b.png">

Errors should then be visible under the section "Console":
<img width="785" alt="bildschirmfoto 2019-01-18 um 09 38 05" src="https://user-images.githubusercontent.com/7721625/51374978-e3f7d580-1b04-11e9-9795-eebdf55ff287.png">

A screenshot / copy of the error text would really help.

## How to (probably) resolve the issue for you
I suppose deleting the directory should fix the issue, replace `YOUR_USER` with your username: 
`C:\Users\YOUR_USER\AppData\Roaming\MQTT-Explorer`

The AppData directory is "hidden" you can 
<img width="803" alt="bildschirmfoto 2019-01-18 um 09 24 54" src="https://user-images.githubusercontent.com/7721625/51374362-156fa180-1b03-11e9-9d07-79c898f50eda.png">

**Comment by miwok72** [comment]
Thanks, here a screenshot according to your instructions. I also tested the version 0.0.5 (portable) again, here I have the same error as mentioned here: [https://community.openhab.org/t/mqtt-exploration-app/64313/8
![mqtt-explorer2](https://user-images.githubusercontent.com/46500817/51390507-c68c3100-1b2f-11e9-96dc-43ff97a09bf3.jpg)
](url)
I do not delete the folder c: \ Users \ xxx \ AppData \ Roaming \ MQTT-Explorer \ so I can still test for you ...

**Comment by thomasnordquist** [comment]
Can you enter the following command at the bottom of the console?
(where the little blue '>' is located).

### Command
`localStorage.getItem('connectionSettings')`

I believe I stored some garbage (data from the view) with the connection object.
If the response contains a password, please obfuscate it.

`
{"visible":true,"host":"localhost","protocol":"mqtt://","port":1883,"tls":false,"certValidation":true,"clientId":"","username":"thomas","password":"","connecting":true,"connectionId":"48803a67","error":{}}
`

**Comment by miwok72** [comment]
here is the output:

`{"visible":true,"host":"192.168.137.29","protocol":"mqtt://","port":1883,"tls":false,"certValidation":false,"clientId":"","username":"openhab","password":"xxx","connecting":false,"connectionId":"9440e910","error":{"code":5}}`

**Comment by thomasnordquist** [comment]
Thank you very much, got it, rookie mistake 😅.
Thanks for your assistance, a rather stupid mistake.
Next version will have a bug reporter and an 'Ooops' screen, in case something linke this will happen again.

<img width="1025" alt="bildschirmfoto 2019-01-18 um 20 51 22" src="https://user-images.githubusercontent.com/7721625/51409676-d709cf00-1b62-11e9-9e78-32ef11faec90.png">

**Comment by miwok72** [comment]
no problem, thank you for this great piece of software!
