### ISSUE TITLE
Ubuntu snap doesn't start the second time

### ISSUE THREAD

**Issue by ysangkok** [thomasnordquist/MQTT-Explorer#367]
On Ubuntu 20.04, I installed mqtt-explorer using snap.

Reproduction: 

I start mqtt-explorer, and close it with the X in the corner.

Now, I try to start mqtt-explorer again from the console, but it just exits with error code 1 but no message.

If I delete ~/snap/mqtt-explorer, I can start it again.

**Comment by thomasnordquist** [comment]
I'll have a look.

**Comment by black-puppydog** [comment]
I stumbled over this issue myself, and found the cause in the [snapcraft forums](https://forum.snapcraft.io/t/some-snaps-will-only-launch-the-first-time/18509/8). The issue for me was that `~/Downloads` was a symlink, not a regular file. I'd expect similar constraints apply to most standard folders, e.g. `~/Music` was mentioned in that thread, too.

**Comment by ysangkok** [comment]
Closing because I stopped using snaps and the issue clutters my list.
