### ISSUE TITLE
Messages are cut off in the tree view.

### ISSUE THREAD

**Issue by hessijames79** [thomasnordquist/MQTT-Explorer#38]
![bildschirmfoto 2019-01-19 um 19 08 59](https://user-images.githubusercontent.com/11688478/51430655-bf901c00-1c1e-11e9-8a52-a01467b95d5f.png)
The tree view is a convenient way to monitor several topics for changes and their respective messages. Unfortunately, the messages are cut off even though there is enough space. See the attached screenshot for reference.

Patrick

**Comment by thomasnordquist** [comment]
I'll check if allowing the values to grow will have any negative impact. 
Usability may be impacted since hovering with the mouse over the values will change the selected topic in the sidebar.
Maybe an option in the settings-sidebar is the correct approach.
I'll take a look

**Comment by thomasnordquist** [comment]
Fixed this with v.0.1.2
