### ISSUE TITLE
Feature: VSCode extension

### ISSUE THREAD

**Issue by aderusha** [thomasnordquist/MQTT-Explorer#39]
First - this tool is amazing, the hierarchical view of MQTT namespace is crazy handy and I've already ditched MQTT Lens and MQTT Spy in favor of this.  Thanks!

Anyway, one feature that would be killer would be IDE integration, so one could have a pane open watching traffic and then copy/paste things in and out into your code on the fly.  I'm a VS Code fan, and I'm making an assumption that bringing this electron app over in to VSCode (also electron) may be do-able.  I've never do-abled anything like that, so I may be completely wrong :P

Thanks again for this awesome tool @thomasnordquist !

**Comment by thomasnordquist** [comment]
Glad you like it.
Building it into an IDE can be done, currently I'm focussing on improving this app.

Btw. Copy&Paste finally work with the v0.0.9 release.
Stupid electron removes the keyboard shortcuts during the release. 🤨

**Comment by thomasnordquist** [comment]
I'm afraid this won't happen any time soon. Moving the project in a different direction.
