### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by uwejan** [thomasnordquist/MQTT-Explorer#401]
Hi, the app crash when the server modifies the subs topics.
here is the screen shot.
![Screenshot-20200708161119-572x548](https://user-images.githubusercontent.com/20250935/86923065-3502eb80-c136-11ea-82f4-e39342884330.png)

**Comment by thomasnordquist** [comment]
What do you mean with
> when the server modifies the subs topics

>

**Comment by uwejan** [comment]
@thomasnordquist Am using webhooks with `vernemq` which allows the hook to return a json response of the modefied topics to sub.
