### ISSUE TITLE
Publish button disappears to the right when long lines are sent

### ISSUE THREAD

**Issue by luebbe** [thomasnordquist/MQTT-Explorer#407]
Steps to reproduce:
- Publish a long line (>200 characters) to a topic
- The publish button disappears to the right and there's no way to get it back apart from restarting MQTT Explorer

![grafik](https://user-images.githubusercontent.com/3872576/87883722-931eb100-ca09-11ea-9d63-9266122a20f6.png)

**Comment by thomasnordquist** [comment]
Have you installed it through the store?
The beta from http://mqtt-explorer.com/ should fix this.

**Comment by luebbe** [comment]
Thank you. Yes, the beta fixes this issue.
But why did you send me to mqtt-explorer.com, where I need to click on the almost invisible "more downloads" link only to be sent to https://github.com/thomasnordquist/MQTT-Explorer/releases/? Doesn't make much sense to me.
