### ISSUE TITLE
Value length cap

### ISSUE THREAD

**Issue by AlanLarsson** [thomasnordquist/MQTT-Explorer#408]
I've run into the problem of the value being capped at around characters 199xx.
Usually it's not a problem except for one specific message that can be severa times that length.

**Comment by Lokhozt** [comment]
Same problem here, the message max length appears to be limited to 20 000 characters with copy to clipboard.

**Comment by thomasnordquist** [comment]
It is a known limitation, I plan to make this configurable.
Limitation is to prevent large messages to exhaust the available memory.

memory = time (message history) x topics (in the tree) x message size
Example: 100 messages * 1000 topics * 20000bytes => ~2GB RAM

**Comment by dleidert** [comment]
Possible duplicates are #504 and #735.
