### ISSUE TITLE
Where to enter the device name in config?

### ISSUE THREAD

**Issue by martijintro** [thomasnordquist/MQTT-Explorer#417]
I can only see connection parameters:
https://support.asplhosting.com/t/sonoff-mini-with-tasmota-6-5-0-seems-to-have-a-problem-with-myqtthub/337/15

Thx for feedback,
Jan

**Comment by martijintro** [comment]
???

**Comment by thomasnordquist** [comment]
You need to connect to your broker.
The "device" name is not part of the url.

**Comment by martijintro** [comment]
Thank you very much for your feedback.

So your tool shows everything - not just a specific topic if i had understand it correctly..?

**Comment by martijintro** [comment]
Here is a good description where you have to enter the `clientId`:
https://support.asplhosting.com/t/sonoff-mini-with-tasmota-6-5-0-seems-to-have-a-problem-with-myqtthub/337/17

Kind regards,
Jan

**Comment by martijintro** [comment]
https://support.asplhosting.com/t/connecting-to-myqtthub-with-mqtt-explorer-com-application-mqtt-explorer-mqttexplorer/239
