### ISSUE TITLE
Pause feature

### ISSUE THREAD

**Issue by thomasnordquist** [thomasnordquist/MQTT-Explorer#42]

**Comment by thomasnordquist** [comment]
Should be rather easy after the search feature.

**Comment by thomasnordquist** [comment]
Should the pause also unsubscribe from the mqtt broker.
Initially I planned to simply stop updating the UI, some brokers may be so busy that unsubscribing is the better way to go.

**Comment by mrwee** [comment]
Maybe both a "stop" and "pause" function. Stop unsubscribes, pause only stops updating the UI

**Comment by thomasnordquist** [comment]
The current pause feature does not unsubscibe, but will log changes until a ~100MB buffer is full.
After the buffer is full, new messages will be discarded.
094d795b39f7e2d32e98fe20b7feac2881cd8432

Also first screenshot of the light theme. Not yet certain of the colors, but coming along nicely.

<img width="884" alt="Bildschirmfoto 2019-04-03 um 17 51 00" src="https://user-images.githubusercontent.com/7721625/55494240-af42e700-563a-11e9-800a-e70cce065709.png">
