### ISSUE TITLE
Support for Decoding Sparkplug-B Payloads

### ISSUE THREAD

**Issue by AccuBytes-TimJ** [thomasnordquist/MQTT-Explorer#427]
This is an essential feature for many IIoT devices as they use CirrusLink's Sparkplug-B specification.
There is already a project for it:
https://github.com/Cirrus-Link/Sparkplug/tree/master/client_libraries/javascript/sparkplug-payload

A selection of decoding options would be great, similar to MQTT.fx

**Comment by greggwon** [comment]
Yes, this would be a great thing to add, including support for sending sparkplug with a list of name and value pairs, birth, death and other certs too.

**Comment by dubyte** [comment]
I am sending a pull request to decode sparkplugb, I am a go developer not a js dev so this first change if accepted I could try to add more support for sending.

https://github.com/thomasnordquist/MQTT-Explorer/pull/582

So this is about be able to see the sparkplug payload in the views and in the diff panels.

**Comment by kc2zgu** [comment]
There seems to be a serious bug with this implementation.

I have no idea what this "Sparkplug" format is, but MQTT Explorer is erroneously trying to use it to decode some topics that are plain text/floating point numbers. It appears to think any string of 5 characters that starts with "5" is Sparkplug, and only shows `{}` for the value (first noticed this with humidity sensors that report values like `55.49` but also confirmed the same thing happens with strings like `50000` `5____` and `5abcd`). I don't even see a way to force the decoding off and show the raw values, so the real content of these topics is basically invisible in MQTT Explorer.

**Comment by bj00rn** [comment]
#792
