### ISSUE TITLE
Purge retained topics hierarchy - recursive removal

### ISSUE THREAD

**Issue by xAPPO** [thomasnordquist/MQTT-Explorer#43]
I would find it very useful to be able to select a 'top' level topic and delete all the retained messages underneath.  A bit like selecting the new retained/delete option but higher in the hierarchy.
Otherwise it's a laborious task....

**Comment by thomasnordquist** [comment]
Thought about it, dismissed it because I did not know where to put the button.
I actually think this is a great feature to purge a tree of unused retained topics.
I'll add it to the todo list.

**Comment by thomasnordquist** [comment]
I think the recursive model is a bit too powerful, it could potentially clear the hole broker and therefore have unforeseen side-effects.
I think I'll add keyboard support, so one can navigate with the arrow keys and clear topics with backspace/delete keys.

**Comment by xAPPO** [comment]
That's a shame as it would have been so useful to me.  Hive include this functionality as a plugin.  I understand the concern but there could be a warning dialog or even an 'advanced features' enable option somewhere.  My topics that I wanted to delete are hundreds of sub topics.

**Comment by jghaanstra** [comment]
Yes please, ran into this recently and ended up purging the entire Mosquitto database to get the job done!

**Comment by thomasnordquist** [comment]
I limited the removal to 50 topics per click, this will be enough to get most of the tiresome work done, without being a "nuke".

Funfact: This feature works well with the search function.
Example: Search for topics containing "PowerState", select the root topic and do the "recursive removal".
The result: All topics containing "PowerState" have been removed.

Will be even more powerful when one can customize the search funktion: Use regex, limit search to topic or message body.

**Comment by thomasnordquist** [comment]
<img width="891" alt="bildschirmfoto 2019-02-18 um 22 18 14" src="https://user-images.githubusercontent.com/7721625/52976807-3578d600-33cb-11e9-98e1-92900aa53a10.png">

**Comment by thomasnordquist** [comment]
Has been released

**Comment by cvladan** [comment]
Woow. Thanks! Great tool!

**Comment by thomasnordquist** [comment]
Can now also been done with de <kbd>Del</kbd> & <kbd>Backspace</kbd> keys.
Released with [v0.3.5](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5).

**Comment by larstobi** [comment]
@thomasnordquist It would be great to enable recursively more than 50 topics. If you're worried about users shooting themselves in the foot, you could make it a hidden "power user" option to enable unlimited recursive deletes. I have several topics from using Home Assistant that I need to delete, and they have thousands of subtopics.

**Comment by tekand** [comment]
@thomasnordquist I can second @larstobi 's opinion. I am also working with Home Assistant and it is quite tiring to reset (delete) all the topics.
Maybe it can be introduced as a hidden setting? Or a key combination?
There are definitely "power users" here who know what they are doing. Please give them the option to do what they want. :)

**Comment by larstobi** [comment]
I used a workaround by using a mqtt CLI to recursively delete them.
