### ISSUE TITLE
Newbie " problem " Probably not an issue

### ISSUE THREAD

**Issue by Trilife** [thomasnordquist/MQTT-Explorer#438]
Gruess Gott aus Kolumbien;

So, I'm can't seem to be able to publish commands:

cmnd/Test1/power ON returns "Command":"Unknown" the same goes for 
cmnd/Test1/power/ON or power/1 etc...

just sending cmnd/Test1/power does return the status...

Cheers;

**Comment by Bubbleman75** [comment]
Same problem here.
Do you have a solution?

**Comment by Trilife** [comment]
> Same problem here.
> Do you have a solution?

Happy New Year!

Yes, I solved the problem, but I cannot remember the solution. I do remember that the solution was provided on the tasmota google group though. Supremely helpful those chaps...

If I remember, I'll ping you. Still on the new year's buzz.

Good luck.

**Comment by Trilife** [comment]
Have you tried "publish" in front of the command?
