### ISSUE TITLE
"Publish" Botton vanish

### ISSUE THREAD

**Issue by CptHolzschnauz** [thomasnordquist/MQTT-Explorer#453]
Every time when i resize or minimize the app window on my mac with high sierra, the "Publish" Button is vanished. Just a restart helps. Looks like it doesn't redraw the grapic after the window is coming back to "normal" size.

**Comment by CptHolzschnauz** [comment]
I found out that the content of the message causes this behaviour. I send somthing like ('value1', 'value2') in raw. After that 
message the button disapears. Is my msg not allowed or is it a bug in the software? The broker has no problems with that msg.

**Comment by CptHolzschnauz** [comment]
The button dissapears because it's right aligned and out of bounds of the window with long mqtt messages posted.
Mayb left align the button is a idea.

**Comment by melyux** [comment]
Why did you close this?

**Comment by CptHolzschnauz** [comment]
I think it's a doublette?
