### ISSUE TITLE
Scrollbar does not work with mouse

### ISSUE THREAD

**Issue by mrwee** [thomasnordquist/MQTT-Explorer#55]
If I try to use the scrollbar with the mouse, I only get the possibility to move the devider left/right. I cannot move the scrollbar up/down. v0.1.3

**Comment by thomasnordquist** [comment]
What do you men exactly?
 - you cannot drag the scrollbar with the mouse?
 - using the scroll-wheel does not work?

**Comment by mrwee** [comment]
I've attached a video which hopefully shows it. I can't use the scrollbar by dragging it up/down, it always only lets me move the separator left/right. I can use the mouse-wheel ok, but often dragging the scrollbar is easier.

[2019-01-30_13-59-14.zip](https://github.com/thomasnordquist/MQTT-Explorer/files/2812605/2019-01-30_13-59-14.zip)

**Comment by thomasnordquist** [comment]
Fixed with: https://github.com/thomasnordquist/MQTT-Explorer/commit/8fdd4f1f0dccbac1e149697eafcc04279e825b8a
Will be released next week
