### ISSUE TITLE
Improve time formatting

### ISSUE THREAD

**Issue by mrwee** [thomasnordquist/MQTT-Explorer#56]
In v0.1.3 date & time is shown as MM/DD/YYYY HH:MM:SS AM/PM.
I'd like to use my local date/time format which is DD-MM-YYYY HH:MM.SS (24H format), so MQTT-Explorer should follow my Windows settings.

**Comment by thomasnordquist** [comment]
I actually thought that it would. 
I'll take a look.

That's how the date s currently formatted, it should use the default time / date formate of your country, if the correct country is selected in you operating system.

https://github.com/thomasnordquist/MQTT-Explorer/blob/0114d938bd1bf2dadf083b209ea80608431d33c0/app/src/components/helper/DateFormatter.tsx#L7-L12

**Comment by thomasnordquist** [comment]
@mrwee Thanks btw. for your input =)

**Comment by mrwee** [comment]
You're welcome. It's a fantastic piece of software!
I'm not that much into programming, but if you look at the attached file, then the upmost part is how Windows display's date+time is shown, mid is how MQTT-Explorer displays's and the bottom part is the Regional format settings.
![2019-01-30_13-53-59](https://user-images.githubusercontent.com/6720774/51982629-d5130a80-2496-11e9-8b31-3bc2aea2f156.png)

**Comment by mrwee** [comment]
Ups. Accidentally closed it.

**Comment by thomasnordquist** [comment]
I added proper time formatting, based on system language.
https://github.com/thomasnordquist/MQTT-Explorer/commit/62cbf6547e3854eed6b45fc2f61af933cb954376

**Comment by mrwee** [comment]
Looking forward :). Keep up the good work!

**Comment by thomasnordquist** [comment]
This has already been released with v0.2.6.
