### ISSUE TITLE
subscribe to topic 

### ISSUE THREAD

**Issue by behroozbc** [thomasnordquist/MQTT-Explorer#599]
Hi 
I am new to mqtt explorer 
I want to know how can subscribe to topic in mqtt-explorer ??
version I use 
![image](https://user-images.githubusercontent.com/20381616/138910355-fa380e30-8647-4ae2-b7e2-e50bc1d5a7ef.png)

**Comment by gizmocuz** [comment]
From what I know you can do this by pressing the 'Advanced' button before you press the 'Connect' button.
Would also love the option to see to (temporarly) subscribe to new topics from the main user interface

**Comment by gizmocuz** [comment]
You're welcome !

**Comment by behroozbc** [comment]
@gizmocuz Thanks 😄
