### ISSUE TITLE
certificate has exprired

### ISSUE THREAD

**Issue by DxrMorgan** [thomasnordquist/MQTT-Explorer#640]
What idiotic situation with "certificate has expired" ??? Certificate is good and working. Another mqtt client work correct. Certificate not self signed. But remain 3 month to end. And app think certificate expired ???

**Comment by davidstx** [comment]
Its the certificate in MQTT Explorer thats expired, you can download a certificate at this link
https://github.com/thomasnordquist/MQTT-Explorer/issues/596

**Comment by bj00rn** [comment]
duplicate of #596
