### ISSUE TITLE
Neither MQTT Explorer 3.5 nor 4.0 beta compatible with latest Raspberry Pi OS

### ISSUE THREAD

**Issue by parasaurolophus** [thomasnordquist/MQTT-Explorer#647]
Thanks for a great tool.

Unfortunately, the latest Raspberry Pi OS uses a version of FUSE by default that is not recognized by the AppImage runtime:

        kirk@pi400:~/Downloads $ ./MQTT-Explorer-0.4.0-beta1-armv7l.AppImage 
        dlopen(): error loading libfuse.so.2
        
        AppImages require FUSE to run. 
        You might still be able to extract the contents of this AppImage 
        if you run it with the --appimage-extract option. 
        See https://github.com/AppImage/AppImageKit/wiki/FUSE 
        for more information

It might be possible to forcibly downgrade at the OS level to the version required by AppImage, but that risks breaking other dependencies.

Meanwhile, there is no snap for the ARM architecture:

        kirk@pi400:~/Downloads $ sudo snap install mqtt-explorer
        error: snap "mqtt-explorer" is not available on stable for this architecture
               (armhf) but exists on other architectures (amd64).

Please consider supporting the Raspberry Pi as an explicit target of your tool's build and integration test process.

Thanks again!

**Comment by mintgroen** [comment]
I 2nd that. Now I need to boot my desktop to debug MQTT clients, because I have a raspberry as desktop in my toolshed.

**Comment by SveinHaDD** [comment]
Love the MQTT Explorer and using it more or less every day. I have several NodeRed and Mosquitto brokers running on RPi on remote sites and access these using VNC. It would be perfect to have MQTT Explorer running on these RPIs to see what is happening on MQTT.  Any chance for a RPi version? It would be greatly appreciated.

**Comment by bj00rn** [comment]
checkout downloads -> https://github.com/thomasnordquist/MQTT-Explorer/releases
