### ISSUE TITLE
MQTT Explorer startet nicht mehr

### ISSUE THREAD

**Issue by appsheld** [thomasnordquist/MQTT-Explorer#650]
Seit heute Fehler beim Start. Popup:
"Die Anwendung konnte nicht korrekt gestartet werden (0x000007b). Klicken Sie...."

Win 11 Enterprise 21H2 Build: 22000.675 Servicepack: Windows Feature Experience Pack 1000.22000.675.0
Keine relevanten Einträge in den Windows-Ereignisprotokollen.
Deinstalliert und neu installiert, keine Änderung.

**Comment by radiergimmy** [comment]
Ich habe das selbe Problem, wie wurde es gelöst?
