### ISSUE TITLE
Can't install on Mac

### ISSUE THREAD

**Issue by donnyyu** [thomasnordquist/MQTT-Explorer#664]
Apple can't check it for malicious software
<img width="249" alt="image" src="https://user-images.githubusercontent.com/20216059/179913261-be41093c-2a59-4312-8dd7-84ac6aeedfca.png">

**Comment by svet-b** [comment]
While I agree that it's a shame that this application appears to have been abandoned, the message you're getting isn't a show-stopper. If you google the message you'll find Apple's instructions for how to run the app regardless: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

**Comment by donnyyu** [comment]
thx @svet-b fixed
