### ISSUE TITLE
Portable version auto-updated and installed the non-portable version

### ISSUE THREAD

**Issue by m-elias** [thomasnordquist/MQTT-Explorer#70]
I'm using the portable version, 0.1.3 auto-updated and installed the non-portable version, which I promptly uninstalled and manually downloaded the 0.2.0 portable. I would have expected the portable version to just download the new portable version and save it in the same directory.

**Comment by thomasnordquist** [comment]
The update mechanism for portable installations is far from perfect.
Auto update should be disabled for the `portable` build. People will still see the update notification and can update when/if they want.

This will require custom builds for all build targets to determine if an auto-update should be attempted.

**Comment by m-elias** [comment]
"Auto update should be disabled for the portable build. People will still see the update notification and can update when/if they want."

That works for me.

**Comment by thomasnordquist** [comment]
In future builds auto-update will be disabled, the next release will be the first that does not auto-updated portable releases.

Fixed with: https://github.com/thomasnordquist/MQTT-Explorer/commit/140054085200ac01978ccfceaeec1d69a790552f

Thanks for reporting =)
