### ISSUE TITLE
how do I undelete??

### ISSUE THREAD

**Issue by Rolzzz** [thomasnordquist/MQTT-Explorer#703]
I clicked "retained" and it deleted the topic, how do I restore the view?
Retained to delete is also bit of a strange way to remove something

**Comment by Mynijo** [comment]
If you have deleted a retained msg, you can "restore" it by resending it to the broker with the retain flag.

[Tooltip](https://i.imgur.com/0O817qr.png)

**Comment by Rolzzz** [comment]
> If you have deleted a retained msg, you can "restore" it by resending it to the broker with the retain flag.
> 
> [Tooltip](https://i.imgur.com/0O817qr.png)

yeah that makes no sense, the image you shared was what caused the deletion of the sensor(s) topic in the first place.

There should be humidity and temperature here, how do I restore them?

![image](https://user-images.githubusercontent.com/29428938/220191488-a42413c7-eec3-46ea-bee5-729731db1830.png)

annoyingly these sensors are now gone from my HomeAssistant sensor list

![image](https://user-images.githubusercontent.com/29428938/220191733-81aca323-c43a-4060-8d0e-a03a77cfecbc.png)

but still see it in my zigee2bmqtt broker

![image](https://user-images.githubusercontent.com/29428938/220191818-2d8486c3-070f-4579-8957-6ea330a9ae32.png)

why provide such an easy delete with no equally easy restore

**Comment by Mynijo** [comment]
This button deletes only the last message sent to this topic.
It does not delete the topic. In fact, it is impossible to delete a topic.

Retained only means that the broker will send you the last message received on this topic.

I can't tell you what is causing your connection problem, but I can tell you that it has nothing to do with the fact that you deleted that message.

**Comment by Rolzzz** [comment]
Strange, I had to rename the sensor in zigbee2bmqtt for it to be seen again in HA, then it populated them in this app.

![image](https://user-images.githubusercontent.com/29428938/220223223-6cfee7e7-1675-43e4-828a-53bd4517329a.png)

either way I am back up and running now, will close this issue
