### ISSUE TITLE
application hiding some topics

### ISSUE THREAD

**Issue by Wildcarde** [thomasnordquist/MQTT-Explorer#704]
I've got a water softener that publishes itself as `$aws/things/<serialnumber>/<Configure Topic>`, while I have confirmed that this is the case using mosquitto debug logs and by testing against it with the home assistant mqtt debugging interface the mqtt explorer interface does not show these published entries.  I suspect this is due to the `$aws` at the front of the topic string but i'm not sure if there's an obvious way to check if this is being filtered, there's no obvious way to turn on debugging through the gui itself.

**Comment by Mynijo** [comment]
If you add "$aws/#" before you connect using the Advanced Connection option, your msgs will be displayed.

**Comment by Wildcarde** [comment]
That worked perfect, thank you!
