### ISSUE TITLE
v0.2.0 portable doesn't save the connection's "MQTT Client ID"

### ISSUE THREAD

**Issue by m-elias** [thomasnordquist/MQTT-Explorer#71]
MQTT Connection, -> Advanced, after I enter my desired MQTT Client ID, -> Back, -> Save, -> Connect, -> Disconnect, -> Advanced, and MQTT Client ID is blank again.

**Comment by thomasnordquist** [comment]
Thanks, for reporting.
Confirmed and fixed.
