### ISSUE TITLE
Please give MQTTX a try, it seems MQTT-Explorer is no longer actively maintained. 

### ISSUE THREAD

**Issue by gujun720** [thomasnordquist/MQTT-Explorer#722]
Hi guys,

I came across a lengthy list of open issues in this repo, some of which date back to 2020. It appears that this project is not actively being maintained anymore.

Considering the increasing number of issues here, I believe that there is a need for an easy-to-use MQTT client with powerful features.

No offense to Thomas, I just want to take this opportunity to introduce MQTTX to you all.

MQTTX is a cross-platform MQTT client that provides an easy-to-use interface to interact with MQTT brokers. This client is designed for developers and testers who need to test and debug their MQTT-based applications. Key features:

- Easy-to-use, chat box for sending/receiving MQTT messages
- Cross-platform, running on Windows, macOS, and Linux
- 100% compliant with MQTT 5.0 and 3.1.1
- Custom colors for different MQTT subscriptions
- Support for one-way and two-way SSL authentication
- Support MQTT over WebSockets
- Payload Format Conversion, support for Hex, Base64, JSON, and Plaintext
- Customized script for MQTT Pub/Sub simulation
- Full logging capabilities
- English, Japanese, Simplified Chinese, Turkish, and Hungarian
- Freely toggle Light/Dark/Night mode

You can find MQTTX on GitHub here: https://github.com/emqx/MQTTX. If you need to download the desktop application, please visit this link: https://mqttx.app/.

Regards

**Comment by huornlmj** [comment]
It's probably not right to discuss a different tool in a tools issues list, but here's my two cents.

- MQTT Explorer  has a more polished feel and is intuitive.  MGTTX is not intuitive.
- Neither seems to have proxy support.  Whoever has this wins for me.

**Comment by hsaturn** [comment]
I won't install Mqttx on my computer. Definitively !

**Comment by gujun720** [comment]
Hi, @rct 

Thank you for the feedback.

I didn't mention I worked for EMQ, since I thought I had already stated this in my profile. I usually check people's profile to learn which companies they work for.

But maybe this is just my way. I should mention where I come from next time.

Believe me, I did check the issue list till 2020. Thomas has not commented the issues for a while.  I think Thomas had a plan for this project. I feel a little bit pity it was not carried out.

**Comment by gujun720** [comment]
@rct 
> I'd love to see MQTT Explorer get some fixes and enhancements. I don't know if the license allows someone else to fork it.

This project is under the license of Attribution-NoDerivatives 4.0. It is very restrictive as it does not allow making derivatives: you may not distribute modified works.
