### ISSUE TITLE
Run MQTT Explorer with Appimage - Error  Binärdatei

### ISSUE THREAD

**Issue by line439** [thomasnordquist/MQTT-Explorer#742]
Hello, 

when trying to run the MQTT Explorer I got following errog: 

bash: ./MQTT.AppImage: Kann die Binärdatei nicht ausführen: Fehler im Format der Programmdatei
Do you have a sulution for it? When I check the properties of my MQTT.Appimage under "Open with" it is mentioned "Geany". So i guess this is wrong. Is there any possibility to change it with the terminal and run it afterwards?

Thanks a lot
line

**Comment by ilgrank** [comment]
In case you haven't noticed, the author is away from the project since years.
Just telling you in case you expected/hoped for a reply from him.
