### ISSUE TITLE
explorer crashes in home assistant on R Pi

### ISSUE THREAD

**Issue by hermannsgithub** [thomasnordquist/MQTT-Explorer#744]
When starting MQTT Explorer it comes up with an empty page, only showing the IP address. If you click on that or some other fields, the explorer crashes and says "I hoped you would never see this window, ....
<img width="810" alt="Screenshot 2023-11-13 at 14 16 53" src="https://github.com/thomasnordquist/MQTT-Explorer/assets/143205696/2d23964e-ffe1-423b-bffa-b01e9df1da34">
"

**Comment by ilgrank** [comment]
In case you haven't noticed, the author is away from the project since years.
Just telling you in case you expected/hoped for a reply from him.

**Comment by bj00rn** [comment]
duplicate #761
