### ISSUE TITLE
MQTT-Explorer won't start on Sonoma

### ISSUE THREAD

**Issue by JCummings49** [thomasnordquist/MQTT-Explorer#758]
When attempting to start MQTT-Explorer, I get the following: 

"MQTT Explorer.app" can't be opened because Apple cannot check it for malicious software.
This software needs to be updated.
Contact the developer for more information.

Installation on M1 MAC mini with 16 GB RAM and Sonoma 14.4

MQTT Explorer release v0.3.5

**Comment by CaseyRo** [comment]
install it through the app store? you won't see the notice then.

**Comment by JCummings49** [comment]
Going to the App Store did work. Silly Apple hoops to jump through.

Thanks, this can be closed.
