### ISSUE TITLE
 Oooooops! I hoped that you would never see this window, but MQTT-Explorer had an unexpected error

### ISSUE THREAD

**Issue by Fooose** [thomasnordquist/MQTT-Explorer#776]
`cleanup@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/3.bundle.js:25338:38
Hi@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:15155:158
Vj@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:15201:297
@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:15274:468
yj@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:15183:102
@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:15067:116
@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:15274:468
fg@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:15067:63
gg@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:15066:498
Mj@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:15184:68
notify@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:1116:12
notifyNestedSubs@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:1189:26
handleChangeWrapper@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:1194:25
dispatch@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/vendors.bundle.js:595:15
dispatchChildActions@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/app.bundle.js:17465:21
@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/app.bundle.js:17462:29
forEach@[native code]
dispatchChildActions@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/app.bundle.js:17461:29
@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/app.bundle.js:17472:29
@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/app.bundle.js:6180:17
invokeFunc@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/app.bundle.js:48109:24
trailingEdge@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/app.bundle.js:48156:24
timerExpired@https://homeassistant.royjones.mywire.org/api/hassio_ingress/YzTM1eRoddJg_nTI25nRp5URQLnDkkSuavNEWS0dbMA/app.bundle.js:48144:26`

**Comment by bj00rn** [comment]
https://github.com/GollumDom/addon-repository?tab=readme-ov-file
