### ISSUE TITLE
Arm71.AppImage won’t run at Bookworm

### ISSUE THREAD

**Issue by testpaul999** [thomasnordquist/MQTT-Explorer#777]
Hi,
I’ll try install at RPi4 with Bookworm and get this error meassage.
![image](https://github.com/thomasnordquist/MQTT-Explorer/assets/35597907/a1bf35f3-e8dd-463d-a24e-a780baef9446)
No hint witch file ar missing.

regards

**Comment by bj00rn** [comment]
try making the file executable

https://www.warp.dev/terminus/chmod-x

**Comment by testpaul999** [comment]
> try making the file executable
> 
> https://www.warp.dev/terminus/chmod-x

Thx for the hint but I’ll do all this before I open the issue 
Regards

**Comment by bj00rn** [comment]
Try
```bash
dpkg-architecture | grep DEB_BUILD_ARCH 
```
What does it say?

**Comment by testpaul999** [comment]
Nothing 
[Gescanntes Dokument 2024-05-13 um 13.23.54.pdf](https://github.com/thomasnordquist/MQTT-Explorer/files/15293620/Gescanntes.Dokument.2024-05-13.um.13.23.54.pdf)

**Comment by bj00rn** [comment]
Try the new pre-release. https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/untagged-e7d548242077decf9893 with an image built for your arch.

**Comment by thomasnordquist** [comment]
Can you try the latest image (beta4)

TestPaul999 ***@***.***> schrieb am Mo., 13. Mai 2024, 13:25:

**Comment by bj00rn** [comment]
@testpaul999 Can you successfully run other AppImages?

What's the output if you run `uname -a`

**Comment by tyeth** [comment]
Just to add my thanks, the 64bit app image loads on my pi5 _once I install libfuse2_
with `sudo apt install libfuse2`

![image](https://github.com/thomasnordquist/MQTT-Explorer/assets/6692083/f1e85fce-f76b-47e6-a1b0-efde208aa56d)

```
uname -a
Linux pi5sd256gb 6.6.28+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux
```

Error seen:
![image](https://github.com/thomasnordquist/MQTT-Explorer/assets/6692083/87b109c2-67fe-4164-a9d0-f905378a555a)
```
Downloads/MQTT-Explorer-0.4.0-beta.6-arm64.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

**Comment by testpaul999** [comment]
> @testpaul999 Can you successfully run other AppImages?
> 
> What's the output if you run `uname -a`

![Uploading image.jpg…]()
