### ISSUE TITLE
Subscribtion to max topic depth doesn't work

### ISSUE THREAD

**Issue by maxbit89** [thomasnordquist/MQTT-Explorer#78]
Hy i am testing a Paho based Client and use MQTT-Explorer to view the Data.
I am publishing a topic with max length (0x10000) with the pattern: 'a/a/a/a/a...' and enforce the last character to be an a:
```
    for(i=0;i<MQTT_MAX_TOPIC;i++) {
        if(i % 2 == 0) { //even
            topicNameBuffer[i] = 'a';
        } else {
            topicNameBuffer[i] = '/';
        }
    }
    topicNameBuffer[MQTT_MAX_TOPIC-2] = 'a';
    topicNameBuffer[MQTT_MAX_TOPIC-1] = '\0';
```
the browser doesn't see this Value.

The funny thing is when i do maxtopiclength with depth 0 like 'tttttt.....':
```
    memset(topicNameBuffer, 't', MQTT_MAX_TOPIC);
    topicNameBuffer[MQTT_MAX_TOPIC-1] = '\0';
```
It works.

The Explorer Viersion i Use is 0.2.0

**Comment by thomasnordquist** [comment]
That is an interesting test-case 😄
I'd guess the reason would be somewhere in the https://github.com/mqttjs/MQTT.js library.
But I can also imagine the UI would be very crammed with a topic depth of ~32.000.

Im a little bit intrigued, may I ask for the reason of this test?

**Comment by maxbit89** [comment]
I also don't see this as "critical". I can't imagine of a useful Usecase. But the MQTT Specs say you can. ^^

**Comment by thomasnordquist** [comment]
Thanks for reporting.
I'll keep it in mind, but I'll probably won't debug this 😅
