### ISSUE TITLE
Verify self-signed certificates with provided certificate

### ISSUE THREAD

**Issue by evstep** [thomasnordquist/MQTT-Explorer#79]
It's possible to have in MQTTExplorer such option like in MQTTBox, select self-signed certificates?

**Comment by thomasnordquist** [comment]
Hmm, I see why this is important.

Unsecure workarounds, for the time being, could be to:
1. uncheck "Validate Certificate" (man-in-the-middle attack is possible, but encryption itself works)
2. Add self-signed certificate to "Trusted Certificates" (other SSL connections may be vulnerable if someone else knows the certificates secret)

It appears that this is technically possible with the `tls.connect` option `options.ca`.
https://nodejs.org/api/tls.html#tls_tls_connect_options_callback

I'm fairly certain that I'll add this security feature in the near future.

**Comment by thomasnordquist** [comment]
What platform (operating system) are you using.
I'll try to fix it today and make a beta-release so you may test it if you like.

**Comment by evstep** [comment]
@thomasnordquist sorry for delay, Ubuntu 18.04

**Comment by thomasnordquist** [comment]
I prepared a beta [AppImage release](https://github.com/thomasnordquist/MQTT-Explorer/releases/download/0.0.0-beta-bucket/MQTT-Explorer-0.2.4-alpha1-x86_64.AppImage).

You'll find the certificate option in the advanced settings.

**Comment by thomasnordquist** [comment]
No comment probably means the test was successful (or not).
Since I've also tested the feature, I close this issue.

Will be part of the next release.
