### ISSUE TITLE
MQTT-Explorer 0.4.0-beta4 SparkplugB decode some strings as "{}"

### ISSUE THREAD

**Issue by LoicGoulefert** [thomasnordquist/MQTT-Explorer#792]
In the latest release of MQTT-Explorer, some payloads seem to be decoded by SparkplugB when they're not meant to be.
This results in some topics to display "{}" instead of the actual payload.

@kc2zgu mentionned [here](https://github.com/thomasnordquist/MQTT-Explorer/issues/427#issuecomment-2091502200
) that some strings (like `5000`) are detected as SparkplugB payloads. I can't reproduce this in my application, but the string "empty" gets decoded by SparkplugB, and rendered as {} in MQTT-Explorer. Turns out that strings of length 5 starting with "e" are decoded wrongly, based on a few manual tests.

**Comment by bj00rn** [comment]
Interesting, the decoder choice logic is pretty naive at the moment it seems, we simply try to decode the payload as sparkplug and if the result is !== undefined we return it. Any suggestion on how to improve the logic is welcome

https://github.com/thomasnordquist/MQTT-Explorer/blob/65b86ac5f665ef8522168b3787183097ada1d6c6/backend/src/index.ts#L52

**Comment by LoicGoulefert** [comment]
Tried to run some more tests, here's what i found:
Strings starting with any of the following characters: 'e', 'E', 'u', 'U', 'm', 'M', 5, with a length that is a multiple of 5, will be decoded as {}.

**Comment by thomasnordquist** [comment]
Thank you, I consider this rather critical.
Maybe we can use part of this implementation https://github.com/thomasnordquist/MQTT-Explorer/pull/493 to make the decoding customizable.

I believe currently we run a decoder chain which is kind of broken

tryToDecodeAsJson
else tryToDecodeAsSparkplugB
else ....

**Comment by bj00rn** [comment]
> Thank you, I consider this rather critical. Maybe we can use part of this implementation #493 to make the decoding customizable.
> 
> I believe currently we run a decoder chain which is kind of broken
> 
> tryToDecodeAsJson else tryToDecodeAsSparkplugB else ....



> Thank you, I consider this rather critical. Maybe we can use part of this implementation #493 to make the decoding customizable.
> 
> I believe currently we run a decoder chain which is kind of broken
> 
> tryToDecodeAsJson else tryToDecodeAsSparkplugB else ....

Would be awesome to prepare for image support to while we are at it.
https://github.com/thomasnordquist/MQTT-Explorer/issues/734

**Comment by jst-mbs** [comment]
> I lack deeper understanding of protobuf decoding, maybe there is a way to inspect the payload to determine if it's sparkplugb.

As someone that has knowledge about Sparkplug but not about JS/TS, I would suggest to inspect the topic structure to detemine if the message is sparkplugb. In my opinion, relying only on the message payload is a bad idea. The sparkplug specifikation can be found here: https://www.eclipse.org/tahu/spec/sparkplug_spec.pdf. The chapter 4.1 is describing the topic structure: 
> All MQTT clients using the Sparkplug specification MUST use the following topic namespace structure:
> ```
> namespace/group_id/message_type/edge_node_id/[device_id]
> ```

The namespace element must be `spBv1.0`.

**Comment by tobehn** [comment]
I think @jst-mbs has a pretty good point. 
`spBv1.0` will always be in the topic of the message. It is at least a good way to double check if decoding might need to be used.
Though in some cases people also send uncompressed messages to the `spBv1.0` namespace. For example i do not know if all STATE messages in SparkplugB are send protobuf compressed.

**Comment by jst-mbs** [comment]
> Though in some cases people send uncompressed messages to the `spBv1.0` namespace. For example i do not know if all STATE messages in SparkplugB are send protobuf compressed.

You are right: The state messages of the 'Host application' is JSON encoded, see chapter '4.2 Sparkplug Host Application'.

**Comment by bj00rn** [comment]
Sidenote there is a package [`sparkplug-payload](https://github.com/eclipse/tahu/blob/master/javascript/core/sparkplug-payload/README.md#sparkplug-payload) that can do decoding/encoding. Might be worth looking into.

**Comment by bj00rn** [comment]
> I think @jst-mbs has a pretty good point. `spBv1.0` will always be in the topic of the message. It is at least a good way to double check if decoding might need to be used. Though in some cases people send uncompressed messages to the `spBv1.0` namespace. For example i do not know if all STATE messages in SparkplugB are send protobuf compressed.

@tobehn @jst-mbs have a look at #793, Will `(topic.match(/spBv1\.0\/[^/]+\/(DDATA|NDATA|NCMD|DCMD|NBIRTH|DBIRTH|NDEATH|DDEATH\/[^/]+\/)/u))` regexp suffice to identify sparkplug payloads?

**Comment by tlifschitz** [comment]
Just for the record, in our application we use custom protobuf messages and the wrongly decoded messages we are seeing are not empty but with random invalid data, as shown below.

Hope @jst-mbs proposal and @bj00rn implementation fixes this issue, thanks!


**Payload 26 bytes**
`b'*\x18\x1a\x16\x08\x0e\xf2\x01\x11\x08\x01\x12\r\x08\x03\x10\x01\x18\x02 \x02HUP\xf0.'`
**Decoded Sparkplug(?)**
`{"body":{"0":26,"1":22,"2":8,"3":14,"4":242,"5":1,"6":17,"7":8,"8":1,"9":18,"10":13,"11":8,"12":3,"13":16,"14":1,"15":24,"16":2,"17":32,"18":2,"19":72,"20":85,"21":80,"22":240,"23":46}}
`

**Payload 36 bytes**
`b'\x12\x0fwmod-din-v0.08b*\x11f/wmod-din-v0.08b'`
**Decoded Sparkplug(?)**
`{"metrics":[{"isHistorical":true,"isNull":true,"doubleValue":3.0644533518218016e-75,"booleanValue":true}],"body":{"0":102,"1":47,"2":119,"3":109,"4":111,"5":100,"6":45,"7":100,"8":105,"9":110,"10":45,"11":118,"12":48,"13":46,"14":48,"15":56,"16":98}}`



![image](https://github.com/thomasnordquist/MQTT-Explorer/assets/15240959/786d791f-2dae-4c66-b7da-d52bb41a17b4)

**Comment by bj00rn** [comment]
> Just for the record, in our application we use custom protobuf messages and the wrongly decoded messages we are seeing are not empty but with random invalid data, as shown below.
> 
> Hope @jst-mbs proposal and @bj00rn implementation fixes this issue, thanks!
> 
> **Payload 26 bytes** `b'*\x18\x1a\x16\x08\x0e\xf2\x01\x11\x08\x01\x12\r\x08\x03\x10\x01\x18\x02 \x02HUP\xf0.'` **Decoded Sparkplug(?)** `{"body":{"0":26,"1":22,"2":8,"3":14,"4":242,"5":1,"6":17,"7":8,"8":1,"9":18,"10":13,"11":8,"12":3,"13":16,"14":1,"15":24,"16":2,"17":32,"18":2,"19":72,"20":85,"21":80,"22":240,"23":46}} `
> 
> **Payload 36 bytes** `b'\x12\x0fwmod-din-v0.08b*\x11f/wmod-din-v0.08b'` **Decoded Sparkplug(?)** `{"metrics":[{"isHistorical":true,"isNull":true,"doubleValue":3.0644533518218016e-75,"booleanValue":true}],"body":{"0":102,"1":47,"2":119,"3":109,"4":111,"5":100,"6":45,"7":100,"8":105,"9":110,"10":45,"11":118,"12":48,"13":46,"14":48,"15":56,"16":98}}`
> 
> ![image](https://private-user-images.githubusercontent.com/15240959/332193252-786d791f-2dae-4c66-b7da-d52bb41a17b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzYyNzMsIm5iZiI6MTcxNjI3NTk3MywicGF0aCI6Ii8xNTI0MDk1OS8zMzIxOTMyNTItNzg2ZDc5MWYtMmRhZS00YzY2LWI3ZGEtZDUyYmI0MWExN2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA3MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMzg3ODc4Mjc2NmNjZWQ5MTYzOTc5ZDQ2MzJkMzQxMWMxNGExYjYwM2JhNGMwNmYzYjQ2NjU3Nzg0MDAxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lRSpyqYHw36ouHNg4tBZnOngY7-xaoei9VbM1cT4oc0)

Thanks, there is clearly a bug with sparkplug decoding. Hopefully we'll get a new beta sorted soon that you can try.
