### ISSUE TITLE
Incorrect display of long and complex JSON payload

### ISSUE THREAD

**Issue by lindhe** [thomasnordquist/MQTT-Explorer#803]
**MQTT Explorer version:** `0.4.0-beta4`

[During some debugging](https://community.openmqttgateway.com/t/missing-discovery-messages-for-nexa-433mhz-devices/3305/24) I found that MQTT Explorer seems to struggle with some JSON payloads.

```console
$ mosquitto_sub -h mqtt.example.com -p 1883 -t 'homeassistant/binary_sensor/Nexa-Security-3-7559323-state/config'
{"stat_t":"+/+/RTL_433toMQTT/Nexa-Security/3/7559323","name":"State","uniq_id":"Nexa-Security-3-7559323-state","val_tpl":"{{ value_json.state | is_defined }}","pl_on":"ON","pl_off":"OFF","device":{"ids":["Nexa-Security-3-7559323"],"cns":[["mac","Nexa-Security-3-7559323"]],"mdl":"Nexa-Security","name":"Nexa-Security-3-7559323","via_device":"OMG_1"}}
```

In MQTT Explorer, it looks like this:

```json
{"uuid":"ac\",\"Nexa-Security-3-7559323\"]],\"mdl\":\"Nexa-Security\",\"name\":\"Nexa-Security-3-7559323\",\"via_device\":\"OMG_1\"}}"}
```

![MQTT Explorer](https://github.com/thomasnordquist/MQTT-Explorer/assets/7773090/c3445b64-ebfc-41a8-9343-65fde954349d)

I tried to find a MWE, this is the best I could come up with:

```console
$ mosquitto_pub -h mqtt.lindhe.io -p 1883 -t debug/foo -m '{"stat_t":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","aaaa":"aaaaa","aaaaaaa":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaa","val_tpl":"{{ value_json.state | is_defined }}","aaaaa":"aa","aaaaaa":"aaa","aaaaaa":{"aaa":["aaaaaaaaaaaaaaaaaaaaaaa"],"aaa":[["mab","aaaaaaaaaaaaaaaaaaaaaaa"]],"aaa":"aaaaaaaaaaaaa","aaaa":"aaaaaaaaaaaaaaaaaaaaaaa","aaaaaaaaaa":"aaaaa"}}'
```

Some notes:

* It seems like length matters, because as far as I can tell I cannot delete a single character from that.
* Complexity seems to matter, because as far as I can tell I cannot remove the `val_tpl` value.
* Maybe special characters like `_` plays a role?
* Note that I _can_ change `mac` into `mab` (like in the example above), but _not_ into `xab`.

**Comment by thomasnordquist** [comment]
There was an issue with the Sparkplug implementation.
Ther is a more recent beta which fixes it.
Sparkplug will be re-added later this week.
