### ISSUE TITLE
Cannot install on Macos

### ISSUE THREAD

**Issue by berrySkies** [thomasnordquist/MQTT-Explorer#805]
Receive following error message when opening the app:

“MQTT Explorer” is damaged and can’t be opened. You should move it to the Bin.

File is MQTT-Explorer-0.4.0-beta4-arm64.dmg

**Comment by hermann4** [comment]
See this comment for the solution:
https://github.com/thomasnordquist/MQTT-Explorer/issues/790#issuecomment-2114942747

**Comment by berrySkies** [comment]
Thank you...sorry I missed earlier issue with the fix.
