### ISSUE TITLE
Y-axis labels truncated with larger numeric values

### ISSUE THREAD

**Issue by Peterkn2001** [thomasnordquist/MQTT-Explorer#84]
In the screenshot below, the values being plotted have a range that are around the 43,000 mark.
The y-axis labels should read 43,100 (bottom) to 43,400 (top) but the leading "4" is being truncated:
![image](https://user-images.githubusercontent.com/35718564/55220267-c9299780-51fe-11e9-9122-31f39caf01d9.png)

**Comment by thomasnordquist** [comment]
Thanks for reporting, I really appreciate it!
Should be an easy fix and will be in the next release.

**Comment by thomasnordquist** [comment]
Numbers will now be abbreviated, also added some more space.
8266a87417dbea4b199744e49c93a58f3f962ca5

10 000 => 10k
10 000 000 => 10m
10 000 000 000 => 10b
10 000 000 000 000 => 10t
